model_arch: MBR_4G
LAI: False
n_cams: 20
n_views: 8
backbone: dinov2-small # dinov2-small, dinov2-base, dinov2-large, dinov2-giant
torch_seed: 0
epoch_freeze_L1toL3: 100  # 10 !!!!!!!!!!!!!!!!! CHANGE TO 10
freeze_triplet_branches: 0
freeze_backbone_warmup: False  # for circle
branch_layer: 3
validation_period: 10

# GPU Settings
half_precision: True
parallel: False
gpu: 0

# Data
BATCH_SIZE: 48 # 128 #48
num_workers_train: 1 #8
num_workers_test: 1

preload_train_device: cpu  # cuda or cpu
preload_train_rate: 1
preload_test_device: cpu  # cuda or cpu
preload_test_rate: 0
preload_num_workers: 1
preload_batch_size: 48

num_epochs: 100
# sampler: random_identity # fixed_order or random_identity
# sampler_batches: /home/serg_fedchn/Homework/6_semester/НИР/object-reidentification/saved_epochs_batches.pkl
# sampler_batches: /home/fedchin/vehicle_reid_itsc2023/saved_epochs_batches.pkl

y_length: 256
x_length: 256

# Losses
mean_losses: False

softmax_loss: torch_ce
label_smoothing: 0.1

metric_loss: fastreidtriplet #Batch_hard_triplet #Batch_hard_triplet #SupCon #RLL
metric_loss_trans: fastreidtriplet
hard_mining: True
triplet_norm: False
triplet_margin: 0.1 # None for Soft Margin Triplet Loss with Batch Hard
triplet_margin_trans: 0.1

circle_softmax: False
margin_circle: 0.35
scale_circle: 64

group_norm: False
pretrain_gropnorm: False
gn_init: kaiming
pretrain_ongroups: True

n_mean: [0.5, 0.5, 0.5]
n_std: [0.5, 0.5, 0.5]

p_hflip: 0.5
p_rerase: 0.5

dataset: Veri776

n_classes: 576
NUM_INSTANCES: 8 #8
images_dir: /home/serg_fedchn/Homework/6_semester/НИР/object-reidentification/dataset/veri_images
query_list_file: /home/serg_fedchn/Homework/6_semester/НИР/object-reidentification/dataset/VeRi/original_veri_query_list.txt
gallery_list_file: /home/serg_fedchn/Homework/6_semester/НИР/object-reidentification/dataset/VeRi/original_veri_test_list.txt
train_list_file: /home/serg_fedchn/Homework/6_semester/НИР/object-reidentification/dataset/VeRi/original_veri_train_list.txt
# images_dir: /home/fedchin/vehicle_reid_itsc2023/dataset/veri_images
# query_list_file: /home/fedchin/vehicle_reid_itsc2023/dataset/VeRi/original_veri_query_list.txt
# gallery_list_file: /home/fedchin/vehicle_reid_itsc2023/dataset/VeRi/original_veri_test_list.txt
# train_list_file: /home/fedchin/vehicle_reid_itsc2023/dataset/VeRi/original_veri_train_list.txt

test_keypoints: /home/serg_fedchn/Homework/6_semester/НИР/object-reidentification/dataset/VeRi/keypoint_orient_test.txt
train_keypoints: /home/serg_fedchn/Homework/6_semester/НИР/object-reidentification/dataset/VeRi/keypoint_orient_train.txt

# Define an optimizer settings
optimizer: Adam # Adam SGD
lr: 0.0001 # 3.5e-5 original Adam 0.0001
weight_decay: 0.0005
bias_lr_factor: 1
momentum: 0.9

# scheduler settings
sched_name: Warm_MultiStep
min_lr: 7.75e-5
milestones: [40, 70, 100]
gamma: 0.1
warmup_factor: 0.0
warmup_iters:  10  # 10 !!!!!!!!!!!!!!!!! CHANGE TO 10
warmup_method: linear

alpha_ce: 0.6 #aka alpha
beta_tri: 1.0  #aka beta
gamma_ce: 0.4
gamma_t: 0.4

# Experiment 
pool: GAP
pool_tripletb: GAP
pool_trans: GAP
linear_num: False
